Support installing versions > 19

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -29,32 +29,39 @@ installer() {
 }
 
 fail() {
-    echo "asdf-graalvm error:" $*
-    exit 1
+  echo "asdf-graalvm error:" $*
+  exit 1
 }
 
 tar_strip_level() {
-	  case "$(uname -s)" in
-		    Linux) echo 1;;
-        Darwin) echo 3;;
-        *) fail "$(uname -s) is not supported" ;;
-    esac
+  case "$(uname -s)" in
+    Linux) echo 1;;
+    Darwin) echo 3;;
+    *) fail "$(uname -s) is not supported" ;;
+  esac
 }
 
 get_variant() {
-	  case "$(uname -s)" in
-		    Linux)
-			      case "$(uname -m)" in
-				        x86_64) echo linux-amd64 ;;
-				        *) fail "$(uname -m) is not supported on linux" ;;
-			      esac ;;
-		    Darwin)
-			      case "$(uname -m)" in
-				        x86_64) echo macos-amd64 ;;
-				        *) fail "$(uname -m) is not supported on macos" ;;
-			      esac ;;
-		    *) fail "$(uname -s) is not supported" ;;
-	  esac
+  local version="$1"
+  case "$(uname -s)" in
+    Linux)
+      case "$(uname -m)" in
+        x86_64) echo linux-amd64 ;;
+        *) fail "$(uname -m) is not supported on linux" ;;
+      esac ;;
+    Darwin)
+      case "$(uname -m)" in
+        x86_64)
+          if version_is_one $version; then
+            echo macos-amd64
+          else
+            echo darwin-amd64
+          fi
+          ;;
+        *) fail "$(uname -m) is not supported on macos" ;;
+      esac ;;
+    *) fail "$(uname -s) is not supported" ;;
+  esac
 }
 
 download_tar() {
@@ -70,10 +77,20 @@ downloaded_file_path() {
   echo "$tmp_download_dir/$pkg_name"
 }
 
+version_is_one() {
+  local version=$1
+  local major_version=$(echo $version | cut -d'.' -f 1)
+  test "$major_version" -eq 1 
+}
+
 download_url() {
   local version=$1
-  local variant=$(get_variant)
-  echo "https://github.com/oracle/graal/releases/download/vm-${version}/graalvm-ce-${version}-${variant}.tar.gz"
+  local variant=$(get_variant $version)
+  if version_is_one $version; then
+    echo "https://github.com/oracle/graal/releases/download/vm-${version}/graalvm-ce-${version}-${variant}.tar.gz"
+  else
+    echo "https://github.com/oracle/graal/releases/download/vm-${version}/graalvm-ce-${variant}-${version}.tar.gz"
+  fi
 }
 
 installer $ASDF_INSTALL_TYPE $ASDF_INSTALL_VERSION $ASDF_INSTALL_PATH
